### ISSUE TITLE
Following your project for a long time

### ISSUE THREAD

**Issue by pcpsp0810csw** [sergkrumas/image_viewer#1]
Can't wait to use it, after all, picasa can't watch gif.
In addition, the 4K screen with picasa effect is not good, because picasa does not natively support 4k.

**Comment by sergkrumas** [comment]
Thanks for your interest! You can support me buying me a PDF book from here https://epubs.siam.org/doi/10.1137/1.9781611971583

my email cjkrumas@gmail.com or just copy the link to the PDF here

**Comment by sergkrumas** [comment]
> Can't wait to use it, after all, picasa can't watch gif. In addition, the 4K screen with picasa effect is not good, because picasa does not natively support 4k.

Thanks for your interest! You can support me buying me a PDF book from here https://epubs.siam.org/doi/10.1137/1.9781611971583

my email [cjkrumas@gmail.com](mailto:cjkrumas@gmail.com) or just copy the link to the PDF here
