### ISSUE TITLE
Краш при запуске. Crash on startup.

### ISSUE THREAD

**Issue by prm88** [sergkrumas/image_viewer#2]
Скачал программу, имел python 3.8.10, из-за чего словил ошибку "AttributeError: module 'functools' has no attribute 'cache'", chatgpt подсказал что functools используется в python >=3.9 и нужно заменить на lru_cache, я сделал это, после чего программа запустилась, но когда я перетаскиваю файл или пытаюсь другим способом открыть картинку, то происходит краш.  Я подумал что проблемы в старой версии, и скачал более новую - 3.10.9, всё равно словал ошибку с зависимостью pywin32 (пути в Path я прописывал), при чем недостаёт эта зависимость и в новой и в старой весии возможно её нужно добавить в файл "install_dependencies.bat", но после её установки всё тоже самое, запускаться - запускается но картинки не открывает, крашится с той же ошибкой. Когда в GUI жму S или viewer тоже крашит. ЛКМ работает, открывается выбор картинки, но когда захожу в папки с картинками - их нет, как будто ищет какой-то несуществующий формат, ПКМ открывает менюшки, но когда пытаюсь хоть что-то переключить - тоже крашит. Что за краш я так и не понял.

**Crash.log:**
Traceback (most recent call last):
  File "C:\Users\Dave\Downloads\image_viewer-master\image_viewer-master\_viewer.pyw", line 2242, in paintEvent
    self._paintEvent(event, painter)
  File "C:\Users\Dave\Downloads\image_viewer-master\image_viewer-master\_viewer.pyw", line 2280, in _paintEvent
    self.draw_content(painter)
  File "C:\Users\Dave\Downloads\image_viewer-master\image_viewer-master\_viewer.pyw", line 2704, in draw_content
    self.draw_secret_hint(painter)
  File "C:\Users\Dave\Downloads\image_viewer-master\image_viewer-master\_viewer.pyw", line 447, in draw_secret_hint
    raise "no data"
TypeError: exceptions must derive from BaseException

**Вот ещё пару строк в консоли были:**
QPaintDevice: Cannot destroy paint device that is being painted
Proccess ID: 10884 Command Arguments: C:\Users\Dave\Downloads\image_viewer-master\image_viewer-master\viewer.pyw, , -aftercrash

Windows 10, свеже установленная, но много зависимостей для других программ скачивал (VS2022, Win11SDK и подобные программы для компиляции других программ), то-есть "сильного дифицита зависимостей" нет. ПК - Intel, Nvidia gtx1070. Зависимости естественно я установил, даже .reg файл применил. Нашёл github через поисковый запрос в google - "picassa image viewer github" первый результат поиска (если интересно :) )

**Comment by sergkrumas** [comment]
>Что за краш я так и не понял.

Это одна из фич, которые представляют мою отсебятину. Если вкратце, то из файла `image_viewer\user_data\deep_secrets.txt` , рандомно будут подтягиваться однострочные и многострочные тексты, если картинку увеличить до упора во вьювере колесом мыши. Текста в файле между собой разделяются пустой строкой. У тебя файла этого не может быть, поскольку он у меня в gitignore, а программа ещё не была в релизе, поэтому я не исправлял это поведение, которое сообщает о неполадке через краш.
Краш я только что пофиксил, тестируй 
https://github.com/sergkrumas/image_viewer/commit/13919cab89a3e4c40441e54bb390d4c354f845f0

>ЛКМ работает, открывается выбор картинки, но когда захожу в папки с картинками - их нет, как будто ищет какой-то несуществующий формат

Этот диалог выбирает папку с картинками, а не саму картинку. Поэтому он не видит картинок вообще, видит только папки. Там в заголовке диалога конечно написано, что надо выбрать именно папку, но, видимо, это не лучшее UX-решение и надо таки дать выбирать картинку?

> словил ошибку с зависимостью pywin32 (пути в Path я прописывал), при чем недостаёт эта зависимость и в новой и в старой весии возможно её нужно добавить в файл "install_dependencies.bat"

Таки обновил файлик
https://github.com/sergkrumas/image_viewer/commit/4fd39308f94e98256eb3e825dfee5c80dbf9ebcb 

> Нашёл github через поисковый запрос в google - "picassa image viewer github" первый результат поиска (если интересно :) )

Да, интересно. Я конечно создаю этот клон для своих нужд, но приятно что людям тоже нужна замена Picasa.  Спасибо за обстоятельный репорт!
Если будут ещё краши, то пиши напрямую, потому что может оказаться так, что это просто напросто какая-то фича реагирует крашем на отсутствие файла.

Вроде ничего не пропустил, жду ответа.

**Comment by sergkrumas** [comment]
Что-то давненько нет фидбэка насчёт исправлений. Ну что же, закрываю репорт.

**Comment by prm88** [comment]
Hi! Протестировал, всё работает отлично, крашей нету!
Да, там оказывается в трёх местах написано "выберите папку", значит я в первый раз не заметил, сори. =)
Сразу не ответил потому что и так очень много времени потратил на поиск просто программы для открытия картинок, эта крашнулась, не понял сразу что за ошибка, и решил затестить другую, вторая заработала, решил на ней посидеть.
Но сейчас обнаружил что меня сильно бесит задержка при открытии картинок, когда открываешь редко не критично, а если например сортируешь фото/картинки то прям жутко бесит. :D Пробовал вот эту riyasy/FlyPhotos, в целом вроде тоже норм, настроек по меньше конечно, правда там баг есть что наслаиваются прозрачные картинки друг на друга, другой чел создал issue но разраб повторить не может, у него всё работает. Я видел что ты убрал дебаг фичу и пофиксил краш, решил скачать твою, попробовать скорость, но блин, при открытии единичных картинок разницы нету, но при открытии фото в папке в которой 1000 изображений то на твоей проге открывает даже дольше, примерно 5-7 секунд вместо ~2 (в той проге тоже есть снизу галерея изображений из папки), хотя внутри когда октрыл, всё работает очень шустро, всё гуд, значит нужно из интерфейса листать. Блин, не помню до переустановки windows какую ПО устанавливал, но по-моему даже при большом кол-во фото в папке оно открывалось всё прям моментально, хотя уже могу врать, вообще выбило из головы что за программа была, но не помню чтобы при открытии фоток меня что-то бесило, значит скорей всего шустро все было, хотя я и фотки редко открывал, так что не уверен..
Так-же лично меня бесит медленный скролл по умолчанию, но слава богу его можно отключить, тогда всё приближает-отдаляет моментально (как в винде настроил) - кайф.
Ноо.. Всё равно спасибо за то что даёшь возможность скачивать прогу всем! Мб это считается нормальной скоростью для всех программ или у ЯП/библиотек свои ограничения есть на скорость чтения, я хз..

**Comment by sergkrumas** [comment]
>правда там баг есть что наслаиваются прозрачные картинки друг на друга, другой чел создал issue но разраб повторить не может, у него всё работает

Странный он человек, мог бы просто попробовать рефрешить фон перед отрисовкой, а он пытается воспроизвести, лол.

>но при открытии фото в папке в которой 1000 изображений то на твоей проге открывает даже дольше, примерно 5-7 секунд вместо ~2 (в той проге тоже есть снизу галерея изображений из папки)

Есть такое. Текущие ограничения, из-за которых я пока и не могу поставить релизный статус программе.
Где-то в пределах 4-6 месяцев я должен реализовать многопоточность и переписать критические куски кода с Python на С/C++, тогда скорость будет около дела. Я сам заметил тормоза уже давно, потому что при разработке постоянно абсолютно всё проверяю в оригинальной программе, а она работает шустрей, потому что написана на С++.
Сам пока мирюсь с этим, потому что своя программа ближе к телу так сказать и для меня там удобные фичи.

>Ноо.. Всё равно спасибо за то что даёшь возможность скачивать прогу всем! 

Да пожалуйста. Правда, видишь, тебе пришлось помучаться с вылавливанием багов. Далеко не каждый будет это делать, даже если можно беспрепятственно скачать программу. Спасибо за репорт ещё раз.

**Comment by sergkrumas** [comment]
А, ну и да. Из-за возможности проигрывания GIF-файлов я могу терпеть текущие тормоза. Тем более возможность нажать паузу и прокручивать кадры колесом мыши в ручном режиме - это для меня очень важно, но, конечно, не для всех.

Ну что же, в пределах года скорость я должен пофиксить. Но пока конкретно сегодня и завтра ничего сделать не могу.

**Comment by prm88** [comment]
Ещё кстати если интересно что именно меня бесит, не понял почему оно читает изображения в "разброс"? Открываю картинки, удаляю лишние, и те которые решил оставить, думал скопом много выделитьи сохранить отдельно в папку, а оно оказывается в разброс листается из-за чего не могу выделить нужные мне по порядку пачкой =(

Оно загружает себе в "память" или куда, и когда листаю, сверху написано 1/100, 2/100 и так по порядку, то есть оно себе какой-то порядок выбрало и ему следует, но не тому порядку который у меня в папке стоит (сортировка по дате).

UPD: Отсортировал в проводнике windows по имени (как по умолчанию) и теперь в программе всё отлично, всё по порядку идёт, так-же как в проводнике. Но например скриншоты я привык сортировать только по дате, чтобы быстро найти последний. Короче фича вроде не обязательная, но если будет то думаю будет большой плюс программе. Хотя мб это как-то можно легко включить в настройках или коде?!, но я не знаю как.

**Comment by sergkrumas** [comment]
>Ещё кстати если интересно что именно меня бесит, не понял почему оно читает изображения в "разброс"? Открываю картинки, удаляю лишние, и те которые решил оставить, думал скопом много выделитьи сохранить отдельно в папку, а оно оказывается в разброс листается из-за чего не могу выделить нужные мне по порядку пачкой =(
>Оно загружает себе в "память" или куда, и когда листаю, сверху написано 1/100, 2/100 и так по порядку, то есть оно себе какой-то порядок выбрало и ему следует, но не тому порядку который у меня в папке стоит (сортировка по дате).

Да, файлы в папке программа вынимает в порядке определяемым именем файлов. 

Как это можно поменять -- если кликнешь правой кнопкой мыши по галерее, то в контекстном меню можешь выбрать нужную сортировку. Но дело в том, что это придётся делать каждый раз, настройки общей нет.

![2024-10-11 18-05-57](https://github.com/user-attachments/assets/39612be9-664b-4aa6-9d5c-534601ddc895)


В проводнике Windows скриншоты могут сортироваться и по имени в том же порядке, как по дате, для этого их надо именовать вот так: сначала год с помощью 4 цифр, потом номер месяца через 2 цифры (если это январь, то через две цифры это будет как "01", нолик спереди обязательно писать, чтобы сортировка по имени работала здесь правильно), потом число месяца через 2 цифры, потом уже час, минуты и секунды в том же формате.

Вот пример того, какие имена штампует мой скриншотер Oxxxy:
![2024-10-11 17-45-15](https://github.com/user-attachments/assets/44066266-b1f8-47fd-b8a1-405cadf39b37)

Вот если так именовать скришоты, то они автоматически будут сортироваться как будто бы по дате но при сортировке по имени.

Попробую сделать так, чтобы порядок файлов засасывался напрямую из открытой папки. Сейчас погуглил по теме, там надо возится с Windows API, что тоже не обещает скорейшего решения проблемы. Но попытаться точно можно и стоит, почему бы нет.

**Comment by sergkrumas** [comment]
Только что попробовал решить проблему с долгой загрузкой папки, в которой около тысячи или больше картинок. Тяни обновления, проверяй и отпишись обязательно. Кажется, дело было не в медленном Python, а в том, что код делал много лишних вещей при чтении данных из папки.

**Comment by prm88** [comment]
Да, теперь кол-во фоток не влияет на скорость открытия - like за оперативны фикс!
Но блин, при открытии каждой картинки все равно задержка в целых ~2 секунды супер не приятная, особенно если надо прям много файлов туда сюда открывать а пользоваться внутренней галерей например не удобно будет. Но дело в том что я не помню как у других программ, интересно глянуть какая там задеркжа при открытии одиночных файлов, неужели тоже 2 сек!? Пока что лень проверить другие imageViewerЫ, мб позже чекну ради интереса, может такое время у большинства это норма, я не знаю. Ибо в той другой что я скачивал (fly) тоже задеркжа на открытие ~2 сек, хотя там C# и C++.

**Comment by sergkrumas** [comment]
Ну что же, я наконец добрался до программы.

>Но блин, при открытии каждой картинки все равно задержка в целых ~2 секунды супер не приятная

Попытался пофиксить. Залил исправление. Проверяй. Отписывайся.

Да, у Picasa Photo Viewer была мгновенная реакция, я помню тестил и обратил на это внимание. Потому что то был чистый EXE-шник написанный на C++, а моя программа это EXE-шник Python'а, который исполняет скрипт `viewer.pyw`.

**Comment by sergkrumas** [comment]
Так, на очереди у нас теперь загрузка порядка из открытой папки проводника. Я посмотрел код альтернативного вьювера написанного на C#, и нашёл там файл нужным с кодом, который решает эту задачу. Осталось причесать этот код для моего приложения, и либо исполнить его на Python, либо исполнить на C++ и подключить к моей проге. Подумаю как поступить, но скорее всего в ноябре сделаю эту фичу.

Ну а многопоточное создание превьшек галереи на следующий год остаётся, видимо. Времени не хватит на написание и отладку.

**Comment by prm88** [comment]
Проверил, да, быстрее стало, спасибо за фиксы!

**Comment by sergkrumas** [comment]
Тебе тоже спасибо, что указал на явные косяки и краши, иначе они не были бы исправлены до релиза, который запланирован на лето 2025 .

**Comment by sergkrumas** [comment]
@eni3ex 
Только что загрузил коммит с согласованием порядка миниатюр с папкой Windows. Загружай, проверяй, отписывайся как оно.
Если будут ещё какие-то замечания помимо порядка миниатюр, то создавай другую тему в Issues, эта себя уже давно изжила.
